### ISSUE TITLE
!displayoptions description not considered as a valid option

### ISSUE THREAD

**Issue by toninio68** [mchangrh/Niles-Alpha#1]
On my test server whenever I'm trying to show the description using the !displayoptions description writen like in the help, the bot throws me a message to tell me that it's not a valid display option.
![Screenshot_20200730_144739](https://user-images.githubusercontent.com/20943583/88924551-bbad7300-d273-11ea-8713-06a178008842.jpg)

**Comment by mchangrh** [comment]
fixed & restarted niles
