### ISSUE TITLE
Description not displaying after turning on setting

### ISSUE THREAD

**Issue by toninio68** [mchangrh/Niles-Alpha#2]
After turning on the !displayoptions description 1 , the description of an event doesnt display on the discord calendar 
![Inkedgcalendar screen_LI](https://user-images.githubusercontent.com/20943583/88942863-1acab200-d28b-11ea-8389-dbe356bef8a1.png)
![brave_PjLKasmTlH](https://user-images.githubusercontent.com/20943583/88943038-48aff680-d28b-11ea-9cee-5e5f28233099.png)

**Comment by mchangrh** [comment]
it seems to be flagging everything as undefined, I'll have to wait to attach a debugger to it
