### ISSUE TITLE
Calendar displaying duplicates events

### ISSUE THREAD

**Issue by toninio68** [mchangrh/Niles-Alpha#3]
The calendar is displaying duplicates event (displaying the latest) when there are multiple events on the same day.
![brave_xSfX7uIAIf](https://user-images.githubusercontent.com/20943583/89590106-6e1ea080-d847-11ea-97fa-431c1327f88a.png)
![brave_wAAVhphua3](https://user-images.githubusercontent.com/20943583/89590111-6fe86400-d847-11ea-8303-786e26984833.png)

**Comment by toninio68** [comment]
and just noticed that if there is an all day event during that day, the all day event wont be displayed

**Comment by mchangrh** [comment]
resolved in niles
